export {default as AdminHome} from './AdminHome'
export {default as Category} from './Category'
export {default as Feedback} from './Feedback'
export {default as Orders} from './Orders'
export {default as OrderDetailAdmin} from '../Admin/Orders/OrderDetail'
export {default as AdminProduct} from './Product'
export {default as Users} from './Users'
export {default as AdminProfile} from './AdminProfile'